### ISSUE TITLE
Saving Data

### ISSUE THREAD

**Issue by drewdeakin** [editor-js/editorjs-php#45]
How would I save the output to a MySQL database?

**Comment by n0str** [comment]
Hello, @drewdeakin. Just save JSON output to a specific field in a table.
For example, you can see the usage of Editorjs-php in the CodeX website engine.

https://github.com/codex-team/codex/blob/master/www/application/classes/Controller/Articles/Modify.php#L90

Here we create instance of EditorJS with content from POST request. And then save data as JSON blob to a table.
```
$editor = new EditorJS($pageContent, Model_Article::getEditorConfig());
...
$article->text         = json_encode(["blocks" => $editor->getBlocks()]);
```

**Comment by drewdeakin** [comment]
Thank you @n0str!
