### ISSUE TITLE
Block tunes API

### ISSUE THREAD

**Issue by johnpuddephatt** [editor-js/editorjs-php#54]
It looks like the new [Block Tunes API](https://editorjs.io/block-tunes-api) is unsupported by editorjs-php at present.

This adds 'tuning' data under the 'tunes' key so block data looks like the following:

```
"type": "paragraph",
"data": {
    "text": "Foo"
},
"tunes": {
    "textVariant": "small"
}
```

**Comment by neSpecc** [comment]
Resolved by #59
