### ISSUE TITLE
Is this plugin dead?

### ISSUE THREAD

**Issue by excitedbox** [editor-js/editorjs-php#55]
Seems this hasn't been updated in a year. Is there an update being worked on?

**Comment by loevgaard** [comment]
I created a library for EditorJS which takes another approach to handling the JSON: https://github.com/Setono/editorjs-php :)

**Comment by eskayamadeus** [comment]
@loevgaard 
I just checked out your package. Great stuff! 
I think the README should be more verbose so we know exactly how to use it without having to dig through the source code...

**Comment by loevgaard** [comment]
I agree @eskayamadeus. A PR would be awesome 🎉
